### ISSUE TITLE
Does opencache serve as a cluster?

### ISSUE THREAD

**Issue by Xuanwo** [datafuselabs/opencache#7]
What will happen if I push the same key with different data to different endpoints?

**Comment by drmingdrmer** [comment]
It will just create a multiverse for the application.

Client-A write `key1=value_x` to cache-node-x; 
Client-B write `key1=value_y` to cache-node-y;

Client-C will see `value_x` if it uses the same algorithm to distribute data as Client-A.
Client-C will see `value_y` if it uses the same algorithm to distribute data as Client-B.
